export const DROPDOWN_SELECT_VALUE = "DROPDOWN_SELECT_VALUE";
export const INPUT_UPDATE_VALUE = "INPUT_UPDATE_VALUE";
export const INPUT_RISE_ERROR = "INPUT_RISE_ERROR";
export const INPUT_RESET_ERROR = "INPUT_RESET_ERROR";
